version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: cases123
    ports:
      - "3306:3306"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "80:80"